export default function Head() {
  return (
    <>
      <title>Bossman's Juicy News</title>
      <meta
        name='description'
        content='Bossmans juicy news from Boss Store, Fenwicks, Newcastle'
      />
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
